spring:
    application:
        name: ops-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
#    redis:
#        database: 1
#        host: ${redis.host:10.180.8.220}
#        pool:
#            max-active: 20
    datasource:
      name: test
      url: ${db.yc_base.url:jdbc:mysql://dce.carapptest.gtmc.com.cn:30143/yc_base?useUnicode=true&amp;characterEncoding=utf8mb4}
      username: ${db.yc_base.username:root}
      password: ${db.yc_base.pwd:123456}
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#    rabbitmq:
#      host: 10.180.4.221
#      port: 5672
#      username: mqadmin
#      password: Pass1234

mybatis:
    basepackage: com.youyou.microservice.auth.server.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: ${ops.auth.port:8778} #启动端口

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: ${eureka.url:http://dce.carapptest.gtmc.com.cn:31432/eureka/}
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/


jwt:
  token-header: Authorization
  expire: ${jwt.yc_base.expire:600}
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key
  params: openid  #demo:openid,test
    
client:
  id: ace-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  pri-key:
    path: client/pri.key
  pub-key:
    path: client/pub.key
track:
  isTacks: true 
  LoggingUrl: /home/yonyou/logs/track.log

redis:
  hostName: ${redis.yc_base.ip:10.180.4.221}
  port: ${redis.yc_base.port:6379}
  password: ${redis.yc_base.password:Pass1234}
  timeout: ${redis.yc_base.timeout:10000}
  testWhileIdle: true 
  maxIdle: ${redis.yc_base.maxIdle:300}  
  maxTotal: ${redis.yc_base.maxTotal:1000}  
  maxWaitMillis: ${redis.yc_base.maxWaitMillis:1000}  
  minEvictableIdleTimeMillis: ${redis.yc_base.minEvictableIdleTimeMillis:300000}  
  numTestsPerEvictionRun: ${redis.yc_base.numTestsPerEvictionRun:1024}  
  timeBetweenEvictionRunsMillis: ${redis.yc_base.timeBetweenEvictionRunsMillis:30000}  
  testOnBorrow: ${redis.yc_base.testOnBorrow:true}  
  expire: 2592000 
auth:
  user:
    pub-key:
      path: jwt/pub.key
