spring:
    application:
        name: ops-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    redis:
      cluster: 
        nodes: ${redis.cluster.nodes:10.180.8.209:7002}
      url: 10.180.8.209
      port: 7002
    datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.180.8.203:3306/yc_base?useUnicode=true&amp;characterEncoding=utf8mb4
       username: test
       password: Pass1q2w

mybatis:
  type-aliases-package: com.youyou.microservice.auth.server.entity
  mapper-locations:  classpath:mapper/**/*.xml
  
mapper: 
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

server:
    port: ${ops.auth.port:8778} #启动端口

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
jwt:
  token-header: Authorization
  expire: ${jwt.yc_base.expire:2592000}
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key
  params: openid  #demo:openid,test
    
client:
  id: ace-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  pri-key:
    path: client/pri.key
  pub-key:
    path: client/pub.key
track:
  isTacks: true 
  LoggingUrl: /home/yonyou/logs/track.log
auth:
  user:
    pub-key:
      path: jwt/pub.key
redis: 
  expire: 2592000
