spring:
    application:
        name: ops-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    redis:
      cluster: 
        nodes: ${redis.cluster.nodes:10.180.8.209:7002}
      url: 10.180.8.209
      port: 7002
    datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.180.8.203:3306/yc_base?useUnicode=true&amp;characterEncoding=utf8mb4
       username: test
       password: Pass1q2w
    servlet:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
server:
    port: ${ops.gate.port:9003} #启动端口
    
    
zuul:
  ignored-services: "*"
  sensitive-headers:
  sensitiveHeaders: 
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: IN_MEMORY #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: ${zuul.yc_base.limit:600}
      refresh-interval: ${zuul.yc_base.limit-interval:60} #default value (in seconds)
      type: #optional
        - user
        - origin
        - url
  routes:
    back:
      path: /admin/**
      serviceId: ops-admin
    auth:
      path: /auth/**
      serviceId: ops-auth
    manager:
      path: /manager/**
      serviceId: ops-admin
    captcha:
      path: /captcha/**
      serviceId: ops-auth
      strip-prefix: false
    wechat:
      path: /wechat/**
      serviceId: wechat-service
    message:
      path: /message/**
      serviceId: ops-mq
    service:
      path: /service/**
      serviceId: ops-service 
    task:
      path: /task/**
      serviceId: ops-task
    alarm:
      path: /alarm/**
      serviceId: ops-alert
  host: 
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  store:
    mysql:
      enabled: true
      
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

gate:
  ignore:
    startWith: /static,/auth/jwt,/captcha/jwt
    addHeader: ${gate.yc_base.addHeader:false}
logging:
  level:
    root: info
    
auth:
  serviceId: ops-auth
  user:
    token-header: Authorization ##所有业务的请求头使用这个来传递JWT
    pub-key:
      path: jwt/pub.key
  client:
    token-header: client-token
    id: ace-gate  #不填则默认读取spring.application.name
    secret: 123456
    pub-key:
      path: client/pub.key

redis:
  expire: ${redis.yc_base.expire:2592000} #2592000 30天
mybatis:
  type-aliases-package: com.yonyou.cloud.zuul.db.entity
  mapper-locations: classpath:zuul/mapper/*.xml
mapper: 
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
