FROM 10.180.4.226/yonyou-dev/jdk-skagent:0.3

COPY ./target/ops-task.jar /ops-task.jar

# COPY ./agent.config /agent/config/

WORKDIR /

EXPOSE 9009

ENTRYPOINT java -javaagent:/agent/skywalking-agent.jar -jar ops-task.jar
