spring:
  data:
    mongodb:
      uri: ${mongodb.uri:mongodb://10.180.4.225:27017/test}
  application:
    name: ops-mq
  rabbitmq:
    password: ${rabbitmq.password:1}
    port: ${rabbitmq.port:5672}
    virtual-host: ${rabbitmq.vhost:paas_dev}
    host: ${rabbitmq.host:121.196.193.149}
    username: ${rabbitmq.username:paasuser}
