logging:
    level:
        tk.mybatis: DEBUG
        com.yonyou.microservice.gate.admin: DEBUG
spring:
    application:
        name: ops-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    datasource:
        name: test
#        :jdbc:mysql://10.180.8.205:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        url: ${db.yc_base.url:jdbc:mysql://10.180.8.203:3306/ag_admin?useUnicode=true&characterEncoding=UTF8}
        username: ${db.yc_base.username:test}
        password: ${db.yc_base.pwd:Pass1q2w}
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  
    rabbitmq:
        host: ${rabbitmq.host:10.180.8.200}
        port : ${rabbitmq.port:32002}
        username: ${rabbitmq.username:rabbituser}
        password: ${rabbitmq.password:123456}
        virtual-host: ${rabbitmq.vhost:/}
        
# 配置zipKin Server的地址
#    zipkin:
#        base-url: http://10.180.4.221:8808
      
mybatis:
    basepackage: com.yonyou.microservice.gate.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: ${ops.admin.port:8760}

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
#    client:
#        registerWithEureka: true
#        fetchRegistry: true
#        serviceUrl:
#            defaultZone: ${eureka.url:http://121.196.193.149:8761/eureka/}
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/
swagger:
    basepackage: com.yonyou.microservice.gate.admin
    service:
        name: Admin Back
        description: Admin Back后端服务
        developer: joy


auth:
  serviceId: ops-auth
  user:
    token-header: Authorization
    pub-key:
      path: jwt/pub.key
  client:
    id: ace-admin
    secret: 123456
    token-header: client-token
    pub-key:
      path: client/pub.key
