logging:
    level:
        tk.mybatis: DEBUG
        com.yonyou.microservice.gate.admin: DEBUG
spring:
    application:
        name: ops-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    datasource: 
      driverClassName : com.mysql.jdbc.Driver
      url: ${db.yc_base.url:jdbc:mysql://localhost:3306:3306/ops_base?useUnicode=true&amp;characterEncoding=utf8mb4}
      username: ${db.yc_base.username:root}
      password: ${db.yc_base.pwd:root}
      hikari:
        dynamic: false #或者不配     
  
    rabbitmq:
        host: ${rabbitmq.host:10.180.8.200}
        port : ${rabbitmq.port:32002}
        username: ${rabbitmq.username:rabbituser}
        password: ${rabbitmq.password:123456}
        virtual-host: ${rabbitmq.vhost:/}
        
# 配置zipKin Server的地址
#    zipkin:
#        base-url: http://10.180.4.221:8808
      
#mybatis:
#    basepackage: com.yonyou.microservice.gate.admin.mapper
#    xmlLocation: classpath:mapper/*.xml

#通用mapper的配置 https://mapperhelper.github.io/docs/1.integration/
mapper: 
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

mybatis: 
  type-aliases-package: com.yonyou.microservice.gate.admin.entity
  mapper-locations: classpath:mapper/*.xml
server:
    port: ${ops.admin.port:8760}

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
#    client:
#        registerWithEureka: true
#        fetchRegistry: true
#        serviceUrl:
#            defaultZone: ${eureka.url:http://121.196.193.149:8761/eureka/}
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/
swagger:
    basepackage: com.yonyou.microservice.gate.admin
    service:
        name: Admin Back
        description: Admin Back后端服务
        developer: joy


auth:
  serviceId: ops-auth
  user:
    token-header: Authorization
    pub-key:
      path: jwt/pub.key
  client:
    id: ace-admin
    secret: 123456
    token-header: client-token
    pub-key:
      path: client/pub.key
